### ISSUE TITLE
macOS 10.2.2更新崩溃

### ISSUE THREAD

**Issue by qiyuey** [HostsTools/macOS#11]
显示内容
Illegal instruction: 4

**Comment by qiyuey** [comment]
个人感觉可能是网络原因，手动更新过hosts文件之后，可以成功更新

**Comment by geemaple** [comment]
hosts里面没有这个 # Modified hosts start ，就崩溃了

**Comment by geemaple** [comment]
需要以下两行
```
# Modified hosts start
# Modified hosts end
```
才能正常使用

**Comment by ZzzM** [comment]
@qiyuey 
@geemaple 
不好意思，最近比较忙，最新的v2.1.0 已修复该问题
