### ISSUE TITLE
MacOS 10.12.3 更新 FC

### ISSUE THREAD

**Issue by MoienBowen** [HostsTools/macOS#13]
HostsTool 2.0.9 (1)

**Comment by ZzzM** [comment]
download HostsTool 2.1.0 ,plz

**Comment by ZzzM** [comment]
@MrBowen 下载最新的版本看看

**Comment by MoienBowen** [comment]
我直接 Download ZIP， 解压后依然 2.0.9 (1)。难道有什么其它下载方式么？

**Comment by ZzzM** [comment]
@MrBowen 版本号显示有误，是我的问题，你应该用的是最新的。方便的话，把你的原hosts发我一份，我看看我这边代码有什么问题。

**Comment by MoienBowen** [comment]
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
fe80::10        localhost

140.205.94.189 taobao.com

以上

**Comment by ZzzM** [comment]
@MrBowen 我已经上传v2.1.0，程序上次更新，现在已更新。

**Comment by MoienBowen** [comment]
可以 Close 了。
不过是什么问题造成的？
两个冒号么？

**Comment by ZzzM** [comment]
@MrBowen 之前没有判断hosts中是否包含"# Modified hosts start",现在加入了
if !OriginalIPStr.contains("# Modified hosts start") ||
                !OriginalIPStr.contains("# Modified hosts end"){
                return true
            }
