### ISSUE TITLE
请求支持合并本地Hosts配置, Request support to merge local Hosts configuration

### ISSUE THREAD

**Issue by evolutionjay** [HostsTools/macOS#17]
# 中文：

现在的这个工具会把原来自己定的host 配置替换掉
因为是搞开发的，有时候自定义一些 hosts ，经常被替换掉不是很爽。

***
# English:

Now this tool will define the original myself to replace any host configuration
Because I am a developer, sometimes the custom some hosts, often be replaced is not good.

**Comment by ZzzM** [comment]
@evolutionjay https://github.com/ZzzM/HostsToolforMac/issues/11 你先按照这个规则，添加自定义hosts，看看还会覆盖吗
