### ISSUE TITLE
建议：不要直接要求用户改读写权限

### ISSUE THREAD

**Issue by Liam0205** [HostsTools/macOS#2]
现在要求将 `/private/etc/hosts` 加读写权限。

我认为这是不良的，因为放开写权限后，其他软件可能恶意修改这个文件。进而，可以将任意流量导入攻击者的服务器。这非常危险。

建议临时 `sudo` 一下，改完就释放 `root` 权限就好了。

**Comment by ZzzM** [comment]
下次更新我会参考您的建议，多谢

**Comment by ZzzM** [comment]
多谢提醒

**Comment by ghost** [comment]
Fix in #3

**Comment by Liam0205** [comment]
赞修复速度！
@ZzzM
