### ISSUE TITLE
升级 2.2.2 点击网络更新，输入管理员密码，显示更新失败

### ISSUE THREAD

**Issue by Jason4V** [HostsTools/macOS#22]
![2017-06-11 7 57 38](https://user-images.githubusercontent.com/385914/27007155-a9277b60-4e7b-11e7-96bf-f450fb9a7d53.png)
详见附件截图

**Comment by ZzzM** [comment]
@ImHUan 你的hosts 是什么样子啊，我这边没问题啊

**Comment by ZzzM** [comment]
@ImHUan 应该是原hosts文件过长引起的

**Comment by ZzzM** [comment]
@ImHUan 我现在更新一下逻辑吧，防止过长引起更新失败。现在第一次更新会全部覆盖，然后以后你就只要在“# 👇My Hosts👇”这下面添加就行了。

**Comment by ZzzM** [comment]
@ImHUan 更新至v2.2.3，具体更新机制，我写了，可以看看

**Comment by Jason4V** [comment]
第一次全覆盖？那岂不是每次你app更新，我都要重新加一遍 My hosts里的内容？不要啊。。。

**Comment by ZzzM** [comment]
@ImHUan 不用，因为加了这个“# 👇My Hosts👇”标识，不管以后怎么更新，你自己的hosts只要写在这个下面，都不会覆盖，第一次全覆盖，是因为你没有生成这个“# 👇My Hosts👇”标识。

**Comment by Jason4V** [comment]
这敢情好啊！让我来试试，多谢！

**Comment by ZzzM** [comment]
@

**Comment by Jason4V** [comment]
好用！多谢陪我折腾了两个issue！我已经是你的老铁了哈哈
