### ISSUE TITLE
[已解决]在 macOS 10.15beta1 使用，提示无法找到文件路径。10.15beta2 可正常使用，无错误提示。

### ISSUE THREAD

**Issue by y010204025** [HostsTools/macOS#32]
![图片](https://user-images.githubusercontent.com/3900301/59679807-560d3d00-91bf-11e9-8d6f-76579c7eeee4.png)
不知道是我操作失误还是其他的什么问题，在 10.14.5 下面是正常的，hosts 文件路径还是在/etc/hosts 下面。

**Comment by ZzzM** [comment]
抱歉，目前没有升级到 macOS 10.15 的设备，暂时无法测试

**Comment by y010204025** [comment]
在 10.15bata2版本可以正常使用，无失败提示，看来是 beta 版本的问题。
